### ISSUE TITLE
Please clarify the README

### ISSUE THREAD

**Issue by timbaileyjones** [beg0/svnpoller#1]
There is another program called svnpoller [1],  and it sends EMAILs of each commit.  I came here looking for that same program, and it wasn't obvious to me that this svnpoller does VISUAL NOTIFICATIONS via X11 of commit messages, until I tried to figure out where to download 'pynotify' from.

Could you please specify that this svnpoller does visual notifications, not email notifications?  It would be a good opportunity to include a screenshot of the visual notifications that this svnpoller does.

[1] https://pypi.python.org/pypi/svnpoller

**Comment by beg0** [comment]
You're right. I'have just specified in th README that it does graphical notification instead of email one.
I hope I will I time to write a better readme soon.
